"""
Report Generator Module
Handles generation of reports in various formats (PDF, CSV, Excel, DOCX, XML)
"""

import os
import io
import csv
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
import logging

# Report generation libraries
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend

from report_models import (
    ReportMetadata, ReportContent, MeasurementResultData,
    StationStatusData, SystemPerformanceData, UserActivityData,
    FrequencyOccupancyData
)

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Main report generation class
    Supports multiple export formats: PDF, CSV, Excel, DOCX, XML
    """
    
    def __init__(self, reports_dir: str = "/app/reports"):
        """
        Initialize report generator
        
        Args:
            reports_dir: Directory to store generated reports
        """
        self.reports_dir = reports_dir
        os.makedirs(reports_dir, exist_ok=True)
        
        # Create subdirectories for different formats
        for format_dir in ["pdf", "csv", "excel", "docx", "xml", "charts"]:
            os.makedirs(os.path.join(reports_dir, format_dir), exist_ok=True)
    
    # ========================================================================
    # PDF Report Generation
    # ========================================================================
    
    def generate_pdf(self, report_content: ReportContent) -> str:
        """
        Generate PDF report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated PDF
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.pdf"
            filepath = os.path.join(self.reports_dir, "pdf", filename)
            
            # Create PDF document
            doc = SimpleDocTemplate(
                filepath,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Container for document elements
            story = []
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1e40af'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=14,
                textColor=colors.HexColor('#2563eb'),
                spaceAfter=12,
                spaceBefore=12
            )
            
            # Title
            story.append(Paragraph(metadata.report_name, title_style))
            story.append(Spacer(1, 0.2 * inch))
            
            # Metadata section
            meta_data = [
                ["Report Type:", metadata.report_type],
                ["Generated By:", metadata.created_by],
                ["Generated At:", metadata.created_at.strftime("%Y-%m-%d %H:%M:%S")],
            ]
            if metadata.description:
                meta_data.append(["Description:", metadata.description])
            
            meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
            meta_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 0.3 * inch))
            
            # Summary section
            if report_content.summary:
                story.append(Paragraph("Executive Summary", heading_style))
                for key, value in report_content.summary.items():
                    story.append(Paragraph(f"<b>{key}:</b> {value}", styles['Normal']))
                    story.append(Spacer(1, 0.1 * inch))
                story.append(Spacer(1, 0.2 * inch))
            
            # Statistics section
            if report_content.statistics:
                story.append(Paragraph("Statistics", heading_style))
                stats_data = [[k, str(v)] for k, v in report_content.statistics.items()]
                stats_table = Table(stats_data, colWidths=[3*inch, 3*inch])
                stats_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e0e7ff')),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 1, colors.grey)
                ]))
                story.append(stats_table)
                story.append(Spacer(1, 0.3 * inch))
            
            # Data section
            if report_content.data:
                story.append(Paragraph("Report Data", heading_style))
                story.append(Spacer(1, 0.1 * inch))
                
                # Convert data to table format
                if len(report_content.data) > 0:
                    # Get headers from first item
                    headers = list(report_content.data[0].keys())
                    table_data = [headers]
                    
                    # Add data rows (limit to first 50 for PDF)
                    for item in report_content.data[:50]:
                        row = [str(item.get(h, '')) for h in headers]
                        table_data.append(row)
                    
                    # Create table
                    col_width = 6.5 * inch / len(headers)
                    data_table = Table(table_data, colWidths=[col_width] * len(headers))
                    data_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82f6')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 8),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f3f4f6')])
                    ]))
                    story.append(data_table)
                    
                    if len(report_content.data) > 50:
                        story.append(Spacer(1, 0.1 * inch))
                        story.append(Paragraph(
                            f"<i>Note: Showing first 50 of {len(report_content.data)} records</i>",
                            styles['Normal']
                        ))
            
            # Charts section
            if report_content.charts:
                story.append(PageBreak())
                story.append(Paragraph("Charts and Visualizations", heading_style))
                for chart_data in report_content.charts:
                    if 'image_path' in chart_data:
                        story.append(Image(chart_data['image_path'], width=5*inch, height=3*inch))
                        story.append(Spacer(1, 0.2 * inch))
            
            # Footer
            story.append(Spacer(1, 0.5 * inch))
            story.append(Paragraph(
                f"<i>Generated by ArgusUI Report Module - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>",
                ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=TA_CENTER)
            ))
            
            # Build PDF
            doc.build(story)
            logger.info(f"PDF report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating PDF report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # CSV Report Generation
    # ========================================================================
    
    def generate_csv(self, report_content: ReportContent) -> str:
        """
        Generate CSV report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated CSV
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.csv"
            filepath = os.path.join(self.reports_dir, "csv", filename)
            
            with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
                # Write metadata as comments
                csvfile.write(f"# Report: {metadata.report_name}\n")
                csvfile.write(f"# Type: {metadata.report_type}\n")
                csvfile.write(f"# Generated By: {metadata.created_by}\n")
                csvfile.write(f"# Generated At: {metadata.created_at}\n")
                if metadata.description:
                    csvfile.write(f"# Description: {metadata.description}\n")
                csvfile.write("\n")
                
                # Write data
                if report_content.data:
                    headers = list(report_content.data[0].keys())
                    writer = csv.DictWriter(csvfile, fieldnames=headers)
                    writer.writeheader()
                    writer.writerows(report_content.data)
            
            logger.info(f"CSV report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating CSV report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # Excel Report Generation
    # ========================================================================
    
    def generate_excel(self, report_content: ReportContent) -> str:
        """
        Generate Excel report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated Excel file
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.xlsx"
            filepath = os.path.join(self.reports_dir, "excel", filename)
            
            # Create workbook
            wb = Workbook()
            
            # Metadata sheet
            ws_meta = wb.active
            ws_meta.title = "Metadata"
            ws_meta.append(["Report Metadata"])
            ws_meta.append(["Report Name", metadata.report_name])
            ws_meta.append(["Report Type", metadata.report_type])
            ws_meta.append(["Generated By", metadata.created_by])
            ws_meta.append(["Generated At", str(metadata.created_at)])
            if metadata.description:
                ws_meta.append(["Description", metadata.description])
            
            # Style metadata
            ws_meta['A1'].font = Font(bold=True, size=14)
            for row in ws_meta.iter_rows(min_row=2, max_row=6, min_col=1, max_col=1):
                for cell in row:
                    cell.font = Font(bold=True)
            
            # Data sheet
            if report_content.data:
                ws_data = wb.create_sheet("Data")
                headers = list(report_content.data[0].keys())
                ws_data.append(headers)
                
                # Style headers
                header_fill = PatternFill(start_color="3B82F6", end_color="3B82F6", fill_type="solid")
                for cell in ws_data[1]:
                    cell.font = Font(bold=True, color="FFFFFF")
                    cell.fill = header_fill
                    cell.alignment = Alignment(horizontal="center")
                
                # Add data rows
                for item in report_content.data:
                    row_data = [item.get(h, '') for h in headers]
                    ws_data.append(row_data)
            
            # Statistics sheet
            if report_content.statistics:
                ws_stats = wb.create_sheet("Statistics")
                ws_stats.append(["Statistics"])
                ws_stats['A1'].font = Font(bold=True, size=14)
                
                for key, value in report_content.statistics.items():
                    ws_stats.append([key, str(value)])
                
                # Style statistics
                for row in ws_stats.iter_rows(min_row=2, max_col=1):
                    for cell in row:
                        cell.font = Font(bold=True)
            
            # Save workbook
            wb.save(filepath)
            logger.info(f"Excel report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating Excel report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # DOCX Report Generation
    # ========================================================================
    
    def generate_docx(self, report_content: ReportContent) -> str:
        """
        Generate DOCX (Word) report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated DOCX file
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.docx"
            filepath = os.path.join(self.reports_dir, "docx", filename)
            
            # Create document
            doc = Document()
            
            # Title
            title = doc.add_heading(metadata.report_name, 0)
            title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            
            # Metadata
            doc.add_heading('Report Information', 2)
            meta_table = doc.add_table(rows=4, cols=2)
            meta_table.style = 'Light Grid Accent 1'
            
            meta_cells = [
                ('Report Type:', metadata.report_type),
                ('Generated By:', metadata.created_by),
                ('Generated At:', str(metadata.created_at)),
                ('Description:', metadata.description or 'N/A')
            ]
            
            for i, (label, value) in enumerate(meta_cells):
                meta_table.rows[i].cells[0].text = label
                meta_table.rows[i].cells[1].text = value
            
            doc.add_paragraph()
            
            # Summary
            if report_content.summary:
                doc.add_heading('Executive Summary', 2)
                for key, value in report_content.summary.items():
                    doc.add_paragraph(f"{key}: {value}", style='List Bullet')
                doc.add_paragraph()
            
            # Statistics
            if report_content.statistics:
                doc.add_heading('Statistics', 2)
                stats_table = doc.add_table(rows=len(report_content.statistics)+1, cols=2)
                stats_table.style = 'Light List Accent 1'
                
                stats_table.rows[0].cells[0].text = 'Metric'
                stats_table.rows[0].cells[1].text = 'Value'
                
                for i, (key, value) in enumerate(report_content.statistics.items(), 1):
                    stats_table.rows[i].cells[0].text = key
                    stats_table.rows[i].cells[1].text = str(value)
                
                doc.add_paragraph()
            
            # Data
            if report_content.data:
                doc.add_heading('Report Data', 2)
                
                if len(report_content.data) > 0:
                    headers = list(report_content.data[0].keys())
                    data_table = doc.add_table(rows=min(len(report_content.data)+1, 51), cols=len(headers))
                    data_table.style = 'Light Grid'
                    
                    # Headers
                    for i, header in enumerate(headers):
                        data_table.rows[0].cells[i].text = header
                    
                    # Data rows (limit to 50)
                    for i, item in enumerate(report_content.data[:50], 1):
                        for j, header in enumerate(headers):
                            data_table.rows[i].cells[j].text = str(item.get(header, ''))
                    
                    if len(report_content.data) > 50:
                        doc.add_paragraph(f"Note: Showing first 50 of {len(report_content.data)} records")
            
            # Footer
            doc.add_paragraph()
            footer_para = doc.add_paragraph(
                f"Generated by ArgusUI Report Module - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            )
            footer_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            
            # Save document
            doc.save(filepath)
            logger.info(f"DOCX report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating DOCX report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # XML Report Generation
    # ========================================================================
    
    def generate_xml(self, report_content: ReportContent) -> str:
        """
        Generate XML report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated XML file
        """
        try:
            import xml.etree.ElementTree as ET
            from xml.dom import minidom
            
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.xml"
            filepath = os.path.join(self.reports_dir, "xml", filename)
            
            # Create root element
            root = ET.Element("Report")
            
            # Metadata
            meta_elem = ET.SubElement(root, "Metadata")
            ET.SubElement(meta_elem, "ReportID").text = metadata.id
            ET.SubElement(meta_elem, "ReportName").text = metadata.report_name
            ET.SubElement(meta_elem, "ReportType").text = metadata.report_type
            ET.SubElement(meta_elem, "GeneratedBy").text = metadata.created_by
            ET.SubElement(meta_elem, "GeneratedAt").text = str(metadata.created_at)
            if metadata.description:
                ET.SubElement(meta_elem, "Description").text = metadata.description
            
            # Summary
            if report_content.summary:
                summary_elem = ET.SubElement(root, "Summary")
                for key, value in report_content.summary.items():
                    ET.SubElement(summary_elem, key).text = str(value)
            
            # Statistics
            if report_content.statistics:
                stats_elem = ET.SubElement(root, "Statistics")
                for key, value in report_content.statistics.items():
                    ET.SubElement(stats_elem, key).text = str(value)
            
            # Data
            if report_content.data:
                data_elem = ET.SubElement(root, "Data")
                for item in report_content.data:
                    item_elem = ET.SubElement(data_elem, "Item")
                    for key, value in item.items():
                        ET.SubElement(item_elem, key).text = str(value)
            
            # Pretty print XML
            xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
            
            # Save to file
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(xml_str)
            
            logger.info(f"XML report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating XML report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # TXT (Plain Text) Report Generation
    # ========================================================================
    
    def generate_txt(self, report_content: ReportContent) -> str:
        """
        Generate plain text report
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated TXT file
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}.txt"
            filepath = os.path.join(self.reports_dir, "txt", filename)
            
            # Ensure txt directory exists
            os.makedirs(os.path.join(self.reports_dir, "txt"), exist_ok=True)
            
            with open(filepath, 'w', encoding='utf-8') as f:
                # Header
                f.write("=" * 80 + "\n")
                f.write(f"{metadata.report_name}\n".center(80))
                f.write("=" * 80 + "\n\n")
                
                # Metadata
                f.write(f"Report ID: {metadata.id}\n")
                f.write(f"Report Type: {metadata.report_type}\n")
                f.write(f"Created By: {metadata.created_by}\n")
                f.write(f"Created At: {metadata.created_at}\n")
                if metadata.description:
                    f.write(f"Description: {metadata.description}\n")
                f.write("\n" + "-" * 80 + "\n\n")
                
                # Summary
                if report_content.summary:
                    f.write("Summary\n")
                    f.write("=" * 7 + "\n\n")
                    for key, value in report_content.summary.items():
                        f.write(f"{key}: {value}\n")
                    f.write("\n" + "-" * 80 + "\n\n")
                
                # Statistics
                if report_content.statistics:
                    f.write("Statistics\n")
                    f.write("=" * 10 + "\n\n")
                    for key, value in report_content.statistics.items():
                        f.write(f"{key}: {value}\n")
                    f.write("\n" + "-" * 80 + "\n\n")
                
                # Data Table
                if report_content.data:
                    f.write("Data\n")
                    f.write("=" * 4 + "\n\n")
                    
                    # Get headers from first data item
                    if report_content.data:
                        headers = list(report_content.data[0].keys())
                        
                        # Calculate column widths
                        col_widths = []
                        for header in headers:
                            max_width = len(str(header))
                            for item in report_content.data:
                                max_width = max(max_width, len(str(item.get(header, ""))))
                            col_widths.append(min(max_width + 2, 30))  # Max 30 chars per column
                        
                        # Print headers
                        header_line = " | ".join(str(h).ljust(w) for h, w in zip(headers, col_widths))
                        f.write(header_line + "\n")
                        f.write("-" * len(header_line) + "\n")
                        
                        # Print rows
                        for item in report_content.data:
                            row_line = " | ".join(
                                str(item.get(h, "")).ljust(w) 
                                for h, w in zip(headers, col_widths)
                            )
                            f.write(row_line + "\n")
                        
                        f.write("\n")
                
                # Footer
                f.write("\n" + "=" * 80 + "\n")
                f.write(f"Generated by ArgusUI - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n".center(80))
                f.write("=" * 80 + "\n")
            
            logger.info(f"TXT report generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating TXT report: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # JasperReports XML Generation
    # ========================================================================
    
    def generate_jasper_xml(self, report_content: ReportContent) -> str:
        """
        Generate JasperReports-compatible XML data file
        
        This creates an XML file that can be used as a data source for JasperReports/iReport.
        The XML follows a structure that can be easily mapped in iReport Designer.
        
        Args:
            report_content: Complete report content
            
        Returns:
            File path of generated XML file
        """
        try:
            metadata = report_content.metadata
            filename = f"{metadata.id}_{metadata.report_type}_jasper.xml"
            filepath = os.path.join(self.reports_dir, "jasper", filename)
            
            # Ensure jasper directory exists
            os.makedirs(os.path.join(self.reports_dir, "jasper"), exist_ok=True)
            
            # Build XML structure
            from xml.etree.ElementTree import Element, SubElement, tostring
            from xml.dom import minidom
            
            # Root element
            root = Element('JasperReport')
            root.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
            root.set('reportName', metadata.report_name)
            
            # Report metadata
            report_meta = SubElement(root, 'ReportMetadata')
            SubElement(report_meta, 'ReportID').text = metadata.id
            SubElement(report_meta, 'ReportType').text = metadata.report_type
            SubElement(report_meta, 'ReportName').text = metadata.report_name
            SubElement(report_meta, 'Description').text = metadata.description or ""
            SubElement(report_meta, 'CreatedBy').text = metadata.created_by
            SubElement(report_meta, 'CreatedAt').text = metadata.created_at
            SubElement(report_meta, 'Status').text = metadata.status
            
            # Filters
            if metadata.filters:
                filters_elem = SubElement(report_meta, 'Filters')
                for key, value in metadata.filters.items():
                    filter_elem = SubElement(filters_elem, 'Filter')
                    filter_elem.set('name', key)
                    filter_elem.text = str(value)
            
            # Report sections
            sections_elem = SubElement(root, 'Sections')
            
            for section in report_content.sections:
                section_elem = SubElement(sections_elem, 'Section')
                section_elem.set('title', section.title)
                
                if section.content:
                    SubElement(section_elem, 'Content').text = section.content
                
                # Tables - each table becomes a DataSet
                if section.tables:
                    tables_elem = SubElement(section_elem, 'Tables')
                    
                    for table_idx, table in enumerate(section.tables):
                        table_elem = SubElement(tables_elem, 'Table')
                        table_elem.set('name', table.get('title', f'Table_{table_idx}'))
                        
                        headers = table.get('headers', [])
                        rows = table.get('rows', [])
                        
                        # Headers
                        headers_elem = SubElement(table_elem, 'Headers')
                        for header in headers:
                            SubElement(headers_elem, 'Header').text = str(header)
                        
                        # Rows
                        rows_elem = SubElement(table_elem, 'Rows')
                        for row in rows:
                            row_elem = SubElement(rows_elem, 'Row')
                            for idx, cell in enumerate(row):
                                cell_elem = SubElement(row_elem, 'Cell')
                                cell_elem.set('column', headers[idx] if idx < len(headers) else f'Col{idx}')
                                cell_elem.text = str(cell)
                
                # Statistics
                if section.statistics:
                    stats_elem = SubElement(section_elem, 'Statistics')
                    for stat in section.statistics:
                        stat_elem = SubElement(stats_elem, 'Statistic')
                        stat_elem.set('label', stat.get('label', ''))
                        stat_elem.text = str(stat.get('value', ''))
                
                # Charts
                if section.charts:
                    charts_elem = SubElement(section_elem, 'Charts')
                    for chart in section.charts:
                        chart_elem = SubElement(charts_elem, 'Chart')
                        chart_elem.set('type', chart.get('type', 'line'))
                        chart_elem.set('title', chart.get('title', ''))
                        
                        # Chart data
                        if 'data' in chart:
                            data_elem = SubElement(chart_elem, 'Data')
                            for data_point in chart['data']:
                                point_elem = SubElement(data_elem, 'Point')
                                for key, value in data_point.items():
                                    SubElement(point_elem, key).text = str(value)
            
            # Summary data (useful for report-level aggregations)
            if report_content.summary:
                summary_elem = SubElement(root, 'Summary')
                for key, value in report_content.summary.items():
                    item_elem = SubElement(summary_elem, 'Item')
                    item_elem.set('key', key)
                    item_elem.text = str(value)
            
            # Pretty print XML
            xml_str = minidom.parseString(tostring(root)).toprettyxml(indent="  ")
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(xml_str)
            
            logger.info(f"JasperReports XML generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating JasperReports XML: {e}", exc_info=True)
            raise
    
    # ========================================================================
    # Chart Generation
    # ========================================================================
    
    def generate_chart(self, chart_data: Dict[str, Any], chart_type: str = "line") -> str:
        """
        Generate chart image for report
        
        Args:
            chart_data: Chart configuration and data
            chart_type: Type of chart (line, bar, pie, scatter)
            
        Returns:
            File path of generated chart image
        """
        try:
            chart_id = chart_data.get('id', datetime.now().strftime('%Y%m%d%H%M%S'))
            filename = f"chart_{chart_id}.png"
            filepath = os.path.join(self.reports_dir, "charts", filename)
            
            fig, ax = plt.subplots(figsize=(10, 6))
            
            if chart_type == "line":
                for series in chart_data.get('series', []):
                    ax.plot(series['x'], series['y'], label=series.get('name', 'Data'))
                ax.legend()
            
            elif chart_type == "bar":
                x_labels = chart_data.get('labels', [])
                values = chart_data.get('values', [])
                ax.bar(x_labels, values)
            
            elif chart_type == "pie":
                labels = chart_data.get('labels', [])
                values = chart_data.get('values', [])
                ax.pie(values, labels=labels, autopct='%1.1f%%')
            
            ax.set_title(chart_data.get('title', 'Chart'))
            ax.set_xlabel(chart_data.get('xlabel', ''))
            ax.set_ylabel(chart_data.get('ylabel', ''))
            ax.grid(True, alpha=0.3)
            
            plt.tight_layout()
            plt.savefig(filepath, dpi=150, bbox_inches='tight')
            plt.close(fig)
            
            logger.info(f"Chart generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating chart: {e}", exc_info=True)
            raise
